### PR TITLE
Update from python 3.5-slim-stretch to python 3.7-slim-stretch

### PR DESCRIPTION
**Pull request by imbatman4**
## Why
Need to update python version to `3.7.9`.

## What
- Recently PR [#663](https://github.com/bebit/user-app-server-side/pull/663) was merged to the `master` branch.
But to merge the latest `master` into `django_dx_improvement` branch, we need to update the two base image from python `3.5.6` to ~`3.7.8`~ `3.7.9`.
- In order to use the `bebit/python-mecab-builder:dev` image we need to send this PR from `dev` (ref https://github.com/bebit/python-mecab-builder/pull/4#issuecomment-674728076). Although I'm not sure if this is the correct way of doing it because there doesn't seem to be any auto build being generated

## Jira
[UG-6043](https://bebit-sw.atlassian.net/browse/UG-6043)

## Additional notes

- Will need to create a new image tag `bebit/python-mecab-builder:dev` before merging this PR - https://github.com/bebit/python-mecab/pull/2
- Will update the README in a different PR.

### CODE REVIEW

**Review by tsmd44 — COMMENTED** [review]
This Dockerfile depends on `bebit/python-mecab-builder:release-1.1` and it depends on `python:3.5-slim-stretch`, so I think we need to update `bebit/python-mecab-builder` at first and create tag (release-1.2?).

**Comment by nakamasato** [comment]
You can use `dev` branch to build docker image before merging just as builder

**Comment by imbatman4** [comment]
> You can use `dev` branch to build docker image before merging just as builder

Thanks! I modified the Dockerfile to point to the dev branch which is specified as its builder in bce14a706366783553fe7a8c25ac7e682814b125 . Is my understanding correct?

**Review by tsmd44 — APPROVED** [review]
Let's apply this change to dev branch, then we can use `bebit/python-mecab-builder:dev` and `bebit/python-mecab:dev` image in user-app-server-side repo while developing `django_dx_improvement`.

I think publishing release-x tag will be fine just before releasing `django_dx_improvement`.

**Comment by imbatman4** [comment]
Thanks, I'll change the base branch from master to `dev` and merge it.

**Review by ike1z — APPROVED** [review]

**Pull request merged**
